repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^(\.pytest_cache|\.ruff_cache|\.venv|vendor)/
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]

  # PHP formatting
  - repo: local
    hooks:
      - id: php-cs-fixer
        name: php-cs-fixer
        entry: composer cs-fix
        language: system
        types: [php]
        files: \.php$

  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
        name: ruff-lint
        files: "^tests/.*\\.py$"
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        files: "^tests/.*\\.py$"

  # Python type checking
  - repo: https://github.com/ComPWA/pyright-pre-commit
    rev: v1.1.407
    hooks:
      - id: pyright
        files: "^tests/.*\\.py$"

  # Formatting for Markdown, JSON, YAML, TOML
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(md|json|yaml|yml|toml)$

default_language_version:
  python: python3

default_install_hook_types: [pre-commit]

exclude: ^(\.pytest_cache|\.ruff_cache|\.venv|vendor)/
