fail_fast: true
exclude: ^(\.pytest_cache|\.ruff_cache|\.venv|vendor|node_modules)/

default_language_version:
  python: python3.13

repos:
  # PHP formatting
  - repo: local
    hooks:
      - id: php-cs-fixer
        name: php-cs-fixer
        entry: backend/vendor/bin/php-cs-fixer fix --using-cache=no --quiet --config=backend/.php-cs-fixer.php --path-mode=intersection --allow-risky=yes
        language: system
        types: [php]

  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
        args: [--fix, --config, tests/pyproject.toml]
        files: ".*\\.py$"
      - id: ruff-format
        args: [--config, tests/pyproject.toml]
        files: ".*\\.py$"

  # Python type checking
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright --project tests
        language: system
        types: [python]
        files: ".*\\.py$"
        pass_filenames: false

  # Other files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [json, yaml, toml, markdown]
        args: [--no-error-on-unmatched-pattern]

  # Final general hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
